### PR TITLE
process pem file with multiple certs when ca contains a chain

### PR DESCRIPTION
**Pull request by chaudhryfaisal**
process pem file with multiple certs when ca contains a chain ( root and sub ca ) and push pem file with chain to nodes instead of only first cert in file

addresses https://github.com/rancher/rke/issues/2597 and https://github.com/rancher/rke/issues/1834

existing PR https://github.com/rancher/rke/pull/2598

### CODE REVIEW

**Review by superseb — APPROVED** [review]

**Comment by chaudhryfaisal** [comment]
@superseb what is next step to Merge this PR?

**Comment by superseb** [comment]
@chaudhryfaisal I've requested review from the team leading this now

**Review by paynejacob — APPROVED** [review]

**Review by thedadams — APPROVED** [review]

**Review by kinarashah — APPROVED** [review]
LGTM, hold off on merging this - will bring it in post v2.6.5 release. Thank you @chaudhryfaisal!

**Comment by Agalin** [comment]
Any progress on this?

**Comment by viq** [comment]
This has been sitting here already approved for nearly half a year, can we please get this in?

**Comment by viq** [comment]
@kinarashah @superseb ping

**Comment by AmanG018** [comment]
@superseb @kinarashah we see this change is not present in any releases after v1.3..when will this change be taken into latest release?

**Comment by superseb** [comment]
Please file a new issue with steps to reproduce, these are the versions (tag) that have the commit:

```
$ git tag --contains 38de6f078287079faa115d2a7a9ac8f6313296e4
v1.3.16
v1.3.17
v1.3.17-rc1
v1.3.17-rc2
v1.3.18
v1.3.18-rc1
v1.3.18-rc2
v1.3.18-rc3
v1.3.18-rc4
v1.3.19-rc1
```

**Pull request merged**
