### PR TITLE
[release/v1.4] Add ACI CNI 6042 variables

### PR DESCRIPTION
**Pull request by jeffinkottaram**
https://github.com/rancher/rancher/issues/45949

### CODE REVIEW

**Comment by kinarashah** [comment]
@jeffinkottaram Changes LGTM, will approve after we merge KDM PR and PR updates data.json.

**Review by snasovich — APPROVED** [review]

**Comment by kinarashah** [comment]
@jeffinkottaram merged KDM PR, you can now run `go generate` to update data.json, thank you!

**Comment by snasovich** [comment]
@jeffinkottaram , also, we've merged CI changes that migrate it from Drone to GH Actions - not sure if GHAs will kick off automatically on push/force-push to source repo. If they don't, you may need to rebase your PR.

**Comment by snasovich** [comment]
@jeffinkottaram , similar to `dev-v2.8` https://releases.rancher.com/kontainer-driver-metadata/dev-v2.7/data.json is now updated

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
