### PR TITLE
add node ip option

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
there is another option which might be safer: add a field call overrideIPAddress and if this field is set, set node-ip. I don't know if setting node-ip to host.address by default will cause any problem.

**Comment by StrongMonkey** [comment]
https://github.com/StrongMonkey/rke.git

**Comment by galal-hussein** [comment]
@StrongMonkey can you resolve the conflicts in plan.go, thanks!

**Comment by StrongMonkey** [comment]
@galal-hussein done

**Comment by alena1108** [comment]
@StrongMonkey `there is another option which might be safer: add a field call overrideIPAddress` - after analyzing rke/k8s stuff, looks like that would be the best option. `address` and `internalAddress` from nodeConfig were originally meant for rke configuration purpose only. `address` - for rke to communicate with k8s components. `internalAddress` - in *some* cases only, it is passed to k8s component so it can be used for intern communication (worker to api server ,api server to etcd). The problem is: `internalAddress` gets defaulted to `address` if not specified. And we can't pass `intenalAddress` flag directly as a node-ip on kubelet start as it can hold external ip value.

As introducing a new flag on api would require changing components like kontainer-engine, custom host registration, I'd suggest we hold on making this fix.

**Comment by deniseschannon** [comment]
Fixed in https://github.com/rancher/rke/pull/444

**Pull request closed without merging**
