### PR TITLE
[WIP till types merged] Accept additional env vars for ingress addon

### PR DESCRIPTION
**Pull request by mrajashree**
Depends on https://github.com/rancher/types/pull/1016
https://github.com/rancher/rancher/issues/16868

### CODE REVIEW

**Comment by alena1108** [comment]
LGTM

**Comment by deniseschannon** [comment]
Could this be updated per @cloudnautique comment? https://github.com/rancher/rke/issues/1104#issuecomment-547731864

**Comment by deniseschannon** [comment]
Also, can we add in the `extraVolumeMounts` arg?

**Comment by mrajashree** [comment]
Closing for https://github.com/rancher/rke/pull/1757

**Pull request closed without merging**
