### PR TITLE
Refactor cloud provider support

### PR DESCRIPTION
**Pull request by galal-hussein**

### CODE REVIEW

**Comment by alexandrem** [comment]
I don't see any cloud-config template for Openstack and we don't have any new RKE type for openstack provider, so I don't see how it can build the INI build with the section (e.g Global) from the type reflection.

Did I miss something?

**Comment by alexandrem** [comment]
Nevermind I saw the new types vendor update with the new nested structs.

Perhaps we should update the cloud provider doc in the README about the new format.

Will the cloud provider form in the Rancher UI be updated dynamically to show those section fields?

**Comment by deniseschannon** [comment]
@alexandrem We plan on updating the readme/docs with the new expected formats and what is available.

For UI, there are some other changes we're doing for advanced options (like this). The expectation in the UI will be for you to put in the correct yaml that you want for your specific cloud provider.

**Comment by dabeck** [comment]
I just tested the new types with cloudProvider `openstack` my config:

```
...
cloud_provider:
  name: openstack
  openstackCloudProvider:
    global:
      auth-url: "https://example.../v3"
      domain-name: "domain"
      password: "password"
      region: "eu-de"
      tenant-id:  "id"
      username: "user"    
    load_balancer:
      subnet-id: "4ba20e2c-bb89-468f-81c6-2c67a4bac419"
      floating-network-id: "0a2228f2-7f8a-45f1-8e09-9039e1d09975"
```

but the generated config is corrupted:

```
$ cat /etc/kubernetes/cloud-config 
[Global,omitempty]
auth-url,omitempty = https://example.../v3
username,omitempty = user
user-id,omitempty = 
password,omitempty = password
tenant-id,omitempty = id
tenant-name,omitempty = 
trust-id,omitempty = 
domain-id,omitempty = 
domain-name,omitempty = domain
region,omitempty = eu-de
ca-file,omitempty = 

[LoadBalancer,omitempty]
lb-version,omitempty = 
use-octavia,omitempty = false
subnet-id,omitempty = 4ba20e2c-bb89-468f-81c6-2c67a4bac419
floating-network-id,omitempty = 0a2228f2-7f8a-45f1-8e09-9039e1d09975
lb-method,omitempty = 
lb-provider,omitempty = 
create-monitor,omitempty = false
monitor-delay,omitempty = 0
monitor-timeout,omitempty = 0
monitor-max-retries,omitempty = 0
manage-security-groups,omitempty = false

[BlockStorage,omitempty]
bs-version,omitempty = 
trust-device-path,omitempty = false
ignore-volume-az,omitempty = false

[Route,omitempty]
router-id,omitempty = 

[Metadata,omitempty]
search-order,omitempty = 
request-timeout,omitempty = 0
```

which leads to a non provisionable cluster.

**Pull request merged**
