### PR TITLE
Add new variables for ACI-CNI 5.2.3.6

### PR DESCRIPTION
**Pull request by siva-muni**
https://github.com/rancher/rancher/issues/41124

### CODE REVIEW

**Comment by LavanyaVaddavalli** [comment]
During the rke binary generation for our testing, one of the steps is to generate a pseudo-version using 'go get..<rke-commit-id>' , and place the pseudo-version in go.mod of kdm repo for 'go generate' and 'go mod tidy'. The 'go mod tidy' is failing with the below error. Not sure if this is the reason for unit test failures.

```go: finding module for package k8s.io/apimachinery/pkg/util/clock
go: downloading k8s.io/apimachinery v0.26.3
github.com/rancher/kontainer-driver-metadata/rke imports
        github.com/rancher/rke/types imports
        github.com/rancher/norman/condition imports
        github.com/rancher/norman/controller imports
        k8s.io/client-go/tools/cache imports
        k8s.io/apimachinery/pkg/util/clock: module k8s.io/apimachinery@latest found (v0.26.3), but does not contain package k8s.io/apimachinery/pkg/util/clock```

**Comment by LavanyaVaddavalli** [comment]
Can you please review the PR @kinarashah @snasovich

**Review by snasovich — CHANGES_REQUESTED** [review]
Please update target branch to https://github.com/rancher/rke/tree/release/v1.4.5

**Comment by siva-muni** [comment]
> Please update target branch to https://github.com/rancher/rke/tree/release/v1.4.5

Thanks @snasovich, We updated to the branch v1.4.5

**Comment by siva-muni** [comment]
Testing in-progress after changing the target branches. Once testing done, will let you know.

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
