### PR TITLE
Update encryption to use JSON tagged structs

### PR DESCRIPTION
**Pull request by dramich**
https://github.com/rancher/rancher/issues/31385

### CODE REVIEW

**Review by kinarashah — DISMISSED** [review]

**Review by luthermonson — DISMISSED** [review]

**Review by superseb — COMMENTED** [review]
This still needs a proper `go generate` right?

**Comment by dramich** [comment]
> This still needs a proper `go generate` right?



> This still needs a proper `go generate` right?

Not anymore. I used `dapper -s` then `go generate` to get the proper changes.

**Review by superseb — DISMISSED** [review]

**Comment by dramich** [comment]
This PR can't be merged until there is a fix in rancher to convert the uppercase versions of the config to the lowercase or those configs will be dropped from the cluster object.

**Comment by dramich** [comment]
@luthermonson @superseb This pr is the same, just pushed and ran the build again to make sure nothing changed.

**Review by luthermonson — APPROVED** [review]

**Pull request merged**
