### PR TITLE
[v1.5] Added ACI-CNI 6.0.3.2 variables

### PR DESCRIPTION
**Pull request by akhilesh-oc**
https://github.com/rancher/rancher/issues/43987

### CODE REVIEW

**Review by snasovich — APPROVED** [review]
LGTM, matches changes from https://github.com/rancher/rke/pull/3466

**Review by kinarashah — APPROVED** [review]
@snasovich changes LGTM, we need to update kdm data here - can do that in this PR after merging KDM PR or in a new followup PR (also need to update branch to dev-v2.8 in codegen)

**Comment by snasovich** [comment]
> @snasovich changes LGTM, we need to update kdm data here - can do that in this PR after merging KDM PR or in a new followup PR (also need to update branch to dev-v2.8 in codegen)

Thank you for reminder, @kinarashah .

@akhilesh-oc , with https://github.com/rancher/kontainer-driver-metadata/pull/1294 merged, please update KDM URL (https://github.com/rancher/rke/blob/186ce0ca0000d2377f6d833eca587b1119b11c10/codegen/codegen.go#L13) to `dev-v2.8` as part of this PR and run updated `go generate`.

**Comment by kinarashah** [comment]
@akhilesh-oc Could you please rerun `go generate`? I missed that we didn't update default k8s version when introducing new versions in the KDM PR, so the build is currently failing. This has been now fixed.

**Review by snasovich — APPROVED** [review]

**Pull request merged**
