### PR TITLE
#2824 firstly remove then add taints

### PR DESCRIPTION
**Pull request by rafal-prasal**
remove taints first
add taints second

### CODE REVIEW

**Comment by rafal-prasal** [comment]
what is that? I forked rke repo as usual
applied change to 1 file (copy/pasted few lines)
and in your build/ci i have this?

    Encountered dirty repo!
    M data/bindata.go
    M data/data.json
    M types/kdm/zz_generated_deepcopy.go
    M types/zz_generated_deepcopy.go
    time="2022-02-04T05:26:25Z" level=fatal msg="exit status 1"

**Comment by kinarashah** [comment]
Hi @rafal-prasal thanks for the PR! 
Our build has validation checks around data vendored in to RKE to ensure it gets all the right k8s versions from https://github.com/rancher/kontainer-driver-metadata. You can usually fetch those with `go generate`, however you don't need to run this now because this has been fixed with https://github.com/rancher/rke/pull/2822. 

You can pull in latest changes, rebase and then run this again. Alternatively, if you just want to test your changes, I usually run `go build` and test with the binary.

**Comment by rafal-prasal** [comment]
@kinarashah hello. 

I have not been doing anything within the repo directory except changing 8 lines of one file
and I am already in sync with master branch. github fetch changes from master button is shadowed.

What can I do now then?

**Comment by kinarashah** [comment]
@rafal-prasal oops, you're right. our master branch is running behind from release/v1.3. Please run `RANCHER_METADATA_URL=https://releases.rancher.com/kontainer-driver-metadata/dev-v2.6/data.json go generate` to workaround issues and update data on the master branch.

**Comment by rafal-prasal** [comment]
will do

**Comment by rafal-prasal** [comment]
since you do not care about master so much then to be honest i do not see the point of fighting here

i  will create pull request to release/v1.3 branch with those 4-5 lines changed

**Pull request closed without merging**
