### PR TITLE
WIP: Updated to read Taints from cluster.yml

### PR DESCRIPTION
**Pull request by nicknezis**

### CODE REVIEW

**Comment by nicknezis** [comment]
Needs https://github.com/rancher/types/pull/829 to be merged first.

**Comment by galal-hussein** [comment]
@nicknezis Thanks for the PR, I can see that you only add the new taints however the pr doesn't really implement the removal of any taint from the config, the PR should handle both cases

**Comment by nicknezis** [comment]
@galal-hussein Oh interesting. I'll try to add it, but first I might need some help understanding how the logic in reconcile.go (that you linked to) relates to the code here https://github.com/rancher/rke/blob/master/cluster/cluster.go#L341

Instead of `syncLabels()` could the call be replaced with a call like seen in up.go? https://github.com/rancher/rke/blob/master/cmd/up.go#L176
(FYI, I'm on Rancher Slack if you think it'll take more nuance to help me understand.) If you think a similar `syncTaints()` call is still needed, I'll add it. Thanks for the help!

**Comment by nicknezis** [comment]
@galal-hussein I updated `syncLabels()` to become `syncLabelsAndTaints()`. Hopefully the logic looks good.

**Comment by nicknezis** [comment]
@galal-hussein Just wanted to follow-up to see if the changes I made 28 days ago were acceptable.

**Comment by orangedeng** [comment]
We already have this merged PR to configure node taints. https://github.com/rancher/rke/pull/1527

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rke/pull/1527

**Pull request closed without merging**
