### PR TITLE
Resolve ip to non-loopback interface if --local is used

### PR DESCRIPTION
**Pull request by GregoireW**
If we use "rke up --local" then process use 'localhost' (127.0.0.1)  as a node. 

Issue is some processes launch containers and check in the containers are made to access the node ip (127.0.0.1). This will fail as 127.0.0.1 will resolve to the container itself.

This PR try to fix that by detecting which is the local host name and associated local ip.  If not resolvable it fallback to 'localhost' '127.0.0.1'. 

Note that this takes the 1st resolved ipV4 from hostname.  I just hope that the ip list always begin with ips from hardware interface and not alias one (like docker one...)

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
I tried this on a fresh RancherOS VM, but unfortunately this wasn't enough to get `--local` to work.

Running the same build against the same VM from another host worked fine so there is still some issue with `--local` to resolve.

**Comment by GregoireW** [comment]
Not sure it will be resolved here or in a new issue, but can you copy/paste the logs you get with '--local'  if possible in the rancher slack ( \#rke ) or here

**Comment by rickard-von-essen** [comment]
I need to reinitialize the VM and reproduce it again, maybe I'll have some time this weekend.

**Comment by galal-hussein** [comment]
@GregoireW Thanks very much for your PR, sorry i didn't realize that there is an attempt to solve this before putting this PR https://github.com/rancher/rke/pull/283, but i think adding net=host for port checker is enough for local deployment to pass

**Comment by galal-hussein** [comment]
Closing this PR in favor of #283 thanks @GregoireW

**Pull request closed without merging**
