### PR TITLE
[release/v1.5] Add ACI CNI 6042 variables

### PR DESCRIPTION
**Pull request by jeffinkottaram**
https://github.com/rancher/rancher/issues/45950

### CODE REVIEW

**Review by snasovich — DISMISSED** [review]

**Comment by kinarashah** [comment]
@jeffinkottaram Changes LGTM, will approve after we merge KDM PR and PR updates data.json.

**Comment by kinarashah** [comment]
@jeffinkottaram merged KDM PR, you can now run `go generate` to update data.json, thank you!

**Comment by snasovich** [comment]
@jeffinkottaram , also, we've merged CI changes that migrate it from Drone to GH Actions - not sure if GHAs will kick off automatically on push/force-push to source repo. If they don't, you may need to rebase your PR.

**Comment by jeffinkottaram** [comment]
@kinarashah, the data.json here: https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json doesn't yet seem to have picked up the changes.

**Comment by snasovich** [comment]
@jeffinkottaram , thank you for letting us know. Seems to be related to Drone -> GHA migration that's going on right now. We will look into this.

**Comment by snasovich** [comment]
@jeffinkottaram , https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json is now updated per https://github.com/rancher/kontainer-driver-metadata/actions/runs/9796074885/job/27049991334.
You should be unblocked updating this.

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
