### PR TITLE
ACI-CNI 5.2.3.4 variables

### PR DESCRIPTION
**Pull request by LavanyaVaddavalli**

### CODE REVIEW

**Comment by snaiksat** [comment]
@kinarashah @snasovich @rosskirkpat

**Comment by rosskirkpat** [comment]
@snaiksat I am no longer able to provide approvals as I have left Rancher. @snasovich and @kinarashah can take this forward

**Review by snasovich — APPROVED** [review]
The changes LGTM. We want https://github.com/rancher/kontainer-driver-metadata/pull/968 reviewed and approved as well though before merging.

Also need 1 more approval.

**Review by jiaqiluo — APPROVED** [review]
LGMT 

Note to reviewers:
- hold on merging until the Nov KDM patches are released
- need to back port to the 1.3 line as the KDM goes into to both 2.6 and 2.7

**Comment by snasovich** [comment]
@LavanyaVaddavalli @snaiksat , this is now merged. It should have gone into 1.4.1 version released yesterday, but was missed. I'm not sure what will the real impact of this missing the cut be on ACI version bump that made it into 1.4.1 - hopefully minimal. Let us know.

Regardless of the above, please also backport these changes to `release/v1.3` branch.

**Comment by snaiksat** [comment]
Thanks @snasovich .

> I'm not sure what will the real impact of this missing the cut be on ACI version bump that made it into 1.4.1

Actually I am not sure I understand this comment. You mention that merging this change into 1.4.1 was missed, but then you reference 1.4.1 in - "what will the real impact of this missing the cut be on ACI version bump that made it into 1.4.1".

> Regardless of the above, please also backport these changes to v1.3 branch.

Okay we will backport these changes to release/v1.3. Once they are backported which version will they be available?

Does this: https://github.com/rancher/kontainer-driver-metadata/pull/968 will also be backported to the corresponding dev-v2.6 branch?

**Comment by snasovich** [comment]
@snaiksat , apologies for the confusing comment. What I mean is that KDM changes to update ACI to 5.2.3.4 were merged prior to the release that happened yesterday (https://github.com/rancher/kontainer-driver-metadata/pull/1017) and then brought into RKE (https://github.com/rancher/rke/pull/3098).

So, versions released yesterday (1.4.1 and 1.3.17) do have new k8s versions (v1.22.16-rancher1-1, v1.23.14-rancher1-1, and v1.24.8-rancher1-1) with ACI images/template updated to 5.2.3.4. However, the changes from this PR (to add `aci_no_wait_for_service_ep_readiness` and `aci_add_external_subnets_to_rdconfig` boolean flags) didn't make it into these releases. They will be included in 1.4.2 (since this PR got merged today) and 1.3.18 (after backport PR is opened and merged).

Answering your other question:
> Does this: https://github.com/rancher/kontainer-driver-metadata/pull/968 will also be backported to the corresponding dev-v2.6 branch?
It was done per https://github.com/rancher/kontainer-driver-metadata/pull/1016 and made it into 1.3.17 release.

**Pull request merged**
