### PR TITLE
[release/v1.6] Add ACI-CNI 6.0.4.2 variables

### PR DESCRIPTION
**Pull request by jeffinkottaram**
https://github.com/rancher/rancher/issues/45952

### CODE REVIEW

**Comment by kinarashah** [comment]
@jeffinkottaram Similar to other PRs, need `data.json` updated here as well.

**Comment by kinarashah** [comment]
@jeffinkottaram KDM PR is now merged https://github.com/rancher/kontainer-driver-metadata/pull/1431

**Comment by jeffinkottaram** [comment]
Thanks @kinarashah. Updated `data.json`.

**Review by snasovich — DISMISSED** [review]
LGTM at a glance. Though PR needs to be rebased - `This branch has conflicts that must be resolved`.
@jeffinkottaram , please resolve that and we should be able to merge shortly.
Edit: I believe the rebase should also result in Github Actions run to satisfy those CI checks.

**Comment by jeffinkottaram** [comment]
@snasovich @kinarashah, rebased the branch. Please have another look.

**Comment by snasovich** [comment]
@jeffinkottaram , apologies - we've just merged https://github.com/rancher/kontainer-driver-metadata/pull/1435 so need another `go generate`. Can you please take care of this asap so we can merge this change?

**Comment by jeffinkottaram** [comment]
@snasovich, could you please see if this resolves it?

**Comment by snasovich** [comment]
@jeffinkottaram , thank you. Re-running CI now and will merge if it passes.

**Pull request merged**
