### PR TITLE
Add Support for Weave Encryption

### PR DESCRIPTION
**Pull request by codezomb**
Add a `weave_password` option to the weave network plugin to enable encryption.

```
network:
  plugin: weave
  options:
    weave_password: 6IuATY7BgWlUGooarP9i
```

### CODE REVIEW

**Comment by codezomb** [comment]
@galal-hussein fixed

**Comment by codezomb** [comment]
@galal-hussein I've added a PR over there. When it's merged I'll update here. Thanks!

**Comment by galal-hussein** [comment]
linking the types PR here https://github.com/rancher/types/pull/508
@alena1108 can you review/merge the types PR ^

**Comment by lnogol** [comment]
Can someone merge this? We urgently need node-to-node encryption in our custom cluster

**Comment by oliverhausler** [comment]
Is there an ETA when this gets merged?

**Comment by alena1108** [comment]
@codezomb could you update the pr with the latest types that has weave api support in? the steps are:

* update vendor.config with the correct commit
* run `trash` (https://github.com/rancher/trash) to pull the dependencies in
* commit vendor changes as a separate commit

**Comment by codezomb** [comment]
@alena1108 	I've updated per your instructions, seems odd that it's now says 137 files updated. Not sure what went wrong.

**Comment by codezomb** [comment]
Here's output from rancher/trash - https://gist.github.com/codezomb/b9f245bea44fd99b80b7caf21949f854

**Pull request closed without merging**
