### PR TITLE
Updated api bool fields with default=true to *bool

### PR DESCRIPTION
**Pull request by rawmind0**
PR rancher/types#1149 is required 

Once required PR is merged, go.mod should be updated with proper rancher/types version before merge

### CODE REVIEW

**Comment by rawmind0** [comment]
Updated integration tests to check type updated fields, `ignore_docker_version` and `upgrade_strategy.node_drain_input.ignore_daemonsets`

**Comment by rawmind0** [comment]
Reverted integration tests update

**Comment by rawmind0** [comment]
Updated go.mod with proper rancher/types commit, rancher/types#1149

**Comment by superseb** [comment]
Talked over the changes, minimum version changed from 1.12 to 1.13 to align with the rest of the repositories, this is not needed for this change but as its included and aligns with the rest of the repositories we can change it.

**Pull request merged**
