### PR TITLE
Added new variables for ACI-CNI 5.2.3.5

### PR DESCRIPTION
**Pull request by siva-muni**

### CODE REVIEW

**Review by snasovich — DISMISSED** [review]
Changes LGTM, but the CI is failing - likely due to changes not yet merged to KDM.

Also, we will need this backported to `release/v1.3`.

**Comment by siva-muni** [comment]
Thanks @snasovich, will do backport to release/v1.3

**Comment by LavanyaVaddavalli** [comment]
@snasovich Please note the backport PR against release/v1.3

[https://github.com/rancher/rke/pull/3130](https://github.com/rancher/rke/pull/3130)

**Comment by snasovich** [comment]
@LavanyaVaddavalli , thank you! The build is still failing though - https://drone-pr.rancher.io/rancher/rke/2639/1/2
@kinarashah , could you please help figure out what needs to be done to make CI pass here?

**Comment by kinarashah** [comment]
@siva-muni Could you run `go generate` and add the generated `data/` changes in a separate commit, that should unblock the CI.

**Comment by siva-muni** [comment]
Thanks @kinarashah for your suggestion, Executed "go generate" and added the changes in separate  commit [d9e0d2c](https://github.com/rancher/rke/pull/3127/commits/d9e0d2ca0a346a8e3885f576a869b14b467a1dd1)

**Review by kinarashah — APPROVED** [review]

**Review by jiaqiluo — APPROVED** [review]

**Comment by jiaqiluo** [comment]
Merged the PR. The changes will be available in the next RC.

**Pull request merged**
