### PR TITLE
Fix manifest concat

### PR DESCRIPTION
**Pull request by blaggacao**
https://github.com/rancher/rke/issues/1149

### CODE REVIEW

**Comment by blaggacao** [comment]
Haven't got a local git-flow set up. Therefore, sorry for the go fmt failure.

**Comment by blaggacao** [comment]
@superseb rc7? It would come in very handy for me :wink:

**Comment by blaggacao** [comment]
@superseb CI fixed. Green now. Merge?

**Comment by superseb** [comment]
This was merged a while back addressing partly the same issue: https://github.com/rancher/rke/pull/1259. This now adds the same logic in another area, this should be cleaned up to have one proper implementation.

Secondly, can you explain why the newline is added in the if block for checking prefix being `---`? I don't see the relation between something not having a prefix and adding a newline to the end if it does.

**Comment by blaggacao** [comment]
If it doesn't have a newline (not all follow good practice) the next file could continue on the same line as the last finished.

This breaks the yaml parser.

**Comment by superseb** [comment]
I get why it's done, I don't understand why the newline should be added if it does not start with `---`. I refactored it in https://github.com/rancher/rke/pull/1388, let me know if that works for you.

**Comment by alena1108** [comment]
Closing as the original issue is addressed with https://github.com/rancher/rke/pull/1388. @blaggacao please open an additional pr if you are interested with that extra new line fix.

**Comment by blaggacao** [comment]
Looks perfect thanks!

**Pull request closed without merging**
