### PR TITLE
Fix incorrect log print on Windows

### PR DESCRIPTION
**Pull request by thxCode**

### CODE REVIEW

**Comment by thxCode** [comment]
@alena1108 , please review this PR. It needs integration tests.

**Comment by moelsayed** [comment]
@thxCode Can you please rebase ?

**Comment by thxCode** [comment]
@moelsayed , rebased

**Comment by thxCode** [comment]
@alena1108 , rebased

**Comment by alena1108** [comment]
https://github.com/rancher/rke/issues/601

**Pull request merged**
