### PR TITLE
Adding DNS Policy support for nginx ingress controller

### PR DESCRIPTION
**Pull request by Oats87**
Works on: https://github.com/rancher/rke/issues/1531

Relies on: https://github.com/rancher/kontainer-driver-metadata/pull/23 and https://github.com/rancher/types/pull/954

### CODE REVIEW

**Comment by superseb** [comment]
With the values being static, we can add validation on the values.

**Comment by superseb** [comment]
The only possible issue I see here is that its only done for ingress controller, and not other addons, which means this needs to be either copy pasted to the other addons later or refactored into a generic approach to adjust this.

**Comment by Oats87** [comment]
OK, I'll work on building validation logic in and get this PR updated.

**Comment by Oats87** [comment]
@superseb added some simple smoke-test validation

**Comment by superseb** [comment]
Cool, thanks. If you can move it to `cluster/validation.go`, this is good to go.

**Pull request merged**
