### PR TITLE
Use data-dir and wal-dir to restore etcd snapshots

### LINKED ISSUE #2547: `rke etcd snapshot-restore` doesn't use this configuration and restores snapshot to a wrong directory
I have custom directories for etcd data and wal files. `rke etcd snapshot-restore` doesn't use this configuration and restores snapshot to a wrong directory.

**RKE version:** v1.2.8

**Docker version:**

```
Client:
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c28948e
 Built:             Mon Apr 12 14:10:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.3
  Git commit:       8728dd246c
  Built:            Mon Apr 12 14:10:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.1
  GitCommit:        12dca9790f4cb6b18a6a7a027ce420145cb98ee7.m
 runc:
  Version:          1.0.0-rc94
  GitCommit:        2c7861bc5e1b3e756392236553ec14a78a09f8bf
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Operating system and kernel:** Arch Linux, 5.12.4-arch1-2

**Type/provider of hosts:** Openstack

**cluster.yml file:**

```yaml
# trimmed
services:
  etcd:
    extra_args:
      # scale etcd disk performance, see https://rancher.com/docs/rancher/v2.x/en/installation/options/etcd/
      data-dir: "/var/lib/rancher/etcd/data/"
      wal-dir: "/var/lib/rancher/etcd/wal/wal_dir"
    extra_binds:
      - "/var/lib/etcd/data:/var/lib/rancher/etcd/data"
      - "/var/lib/etcd/wal:/var/lib/rancher/etcd/wal"
# trimmed
```

**Steps to Reproduce:**

1. Create RKE cluster using custom paths for `data-dir` and `wal-dir` arguments
2. Create a snapshot with `rke etcd snapshot-save`
3. Restore snapshot with `rke etcd snapshot-restore`

**Results:**

The snapshot is restored into a directory, which is not mounted to the `etcd` containers, etcd uses the pre-restore data.

### PR DESCRIPTION
**Pull request by Zebradil**
#2547

### CODE REVIEW

**Comment by superseb** [comment]
Thanks, will take a look

**Comment by Zebradil** [comment]
Got some time to take a look this?

**Comment by Zebradil** [comment]
@superseb is there a chance this will be merged?

**Comment by superseb** [comment]
Can you make it 1 commit? And the only question I have on this why we are moving away from `mv` and now are using `cp` while we are still moving files around but just in subdirectories.

**Review by superseb — CHANGES_REQUESTED** [review]
^^

**Comment by Zebradil** [comment]
Thanks for taking a look on this. 

I don't remember already, why `mv` got changed to `cp`. There was a reason for that most likely. I'll check a version with `mv` to see why it didn't work.

**Comment by Zebradil** [comment]
@superseb sorry, just managed to get to this topic.

I replaced `cp` back to `mv` and also fixed another issue, which happens when old WAL files are not deleted. In this case etcd fails with error: "etcdmain: wal: crc mismatch". And squashed this to a single commit.

**Comment by Zebradil** [comment]
@superseb Any chance to have another look on that?

**Comment by superseb** [comment]
@Zebradil CI is failing

**Comment by Zebradil** [comment]
@superseb I fixed formatting and squashed commits again. Now there is another error in CI, which doesn't seem actionable for me.

**Comment by superseb** [comment]
@Zebradil Can you create a new PR against `release/v1.3` so Drone picks it up for proper CI? Then I can merge it.

**Comment by Zebradil** [comment]
@superseb done

**Comment by Zebradil** [comment]
This is ridiculous, I'm tired updating my branch and resolving conflicts.

**Pull request closed without merging**
