### PR TITLE
Use the node's architecture to build etcd process

### PR DESCRIPTION
**Pull request by zhaofengli**
This allows for mixed-architecture etcd clusters.

### CODE REVIEW

**Comment by leodotcloud** [comment]
@zhaofengli What architecture are you trying to run on? The changes themselves look ok, but we might need similar architecture enabled in the docker images.

**Comment by zhaofengli** [comment]
Thanks for the response! For me, it's currently arm64.

**Comment by thies226j** [comment]
Can this be updated?
The standard Etcd image already supports arm64, but needs the ETCD_UNSUPPORTED_ARCH flag set to arm64.

**Comment by leodotcloud** [comment]
@cjellick can you please look into this?

**Comment by cjellick** [comment]
302 @superseb @deniseschannon

**Review by superseb — APPROVED** [review]

**Pull request merged**
